### ISSUE TITLE
Error osmread 

### ISSUE THREAD

**Issue by joaoserpaD** [JHMeusener/osm2xodr#2]
Hi, im trying to parse a osm file to a openDrive file (xodr). Changed the paths in the main. Downloaded the required libs and run it. I have a error in the function giveMaxMinLongLat in the for, the traceback goes inside the osmread lib and return a error KeyError: 'changeset'.

Can anyone help me?

**Comment by KangChou** [comment]
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/osm2xodr/main.py", line 3, in <module>
    from .OSMParser.testing import TestEntity, _test_nodes, testSimpleRoad, test_3WayTCrossing2
ImportError: attempted relative import with no known parent package

**Comment by JHMeusener** [comment]
I cant help with the osmread library.

**Comment by jayaraj0517** [comment]
I am trying to load openDrive file (xodr) it is loading we roads are not getting some portion of data is missing could u tell me why i am getting this kind of problem.

weather is having osm download problem or openDrive file (xodr).

**Comment by artificialhumanbeing** [comment]
Hello, same issue. How did you solve this problem?
