### ISSUE TITLE
Traceback (most recent call last):   File "D:/Simulation_box/WindowsNoEditor/PythonAPI/osm2xodr/main.py", line 3, in <module>     from .OSMParser.testing import TestEntity, _test_nodes, testSimpleRoad, test_3WayTCrossing2 ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by KangChou** [JHMeusener/osm2xodr#3]
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/osm2xodr/main.py", line 3, in <module>
    from .OSMParser.testing import TestEntity, _test_nodes, testSimpleRoad, test_3WayTCrossing2
ImportError: attempted relative import with no known parent package

**Comment by JHMeusener** [comment]
do you have an old commit? There should not be a dot before the OSMParser in the import statement of the main.py
