### ISSUE TITLE
Traceback (most recent call last):   File "D:/Simulation_box/WindowsNoEditor/PythonAPI/osm_open/osm_xr.py", line 26, in <module>     xodr_data = carla.Osm2Odr.convert(osm_data, settings) RuntimeError: No edges loaded.

### ISSUE THREAD

**Issue by KangChou** [JHMeusener/osm2xodr#4]
Traceback (most recent call last):
  File "D:/Simulation_box/WindowsNoEditor/PythonAPI/osm_open/osm_xr.py", line 26, in <module>
    xodr_data = carla.Osm2Odr.convert(osm_data, settings)
RuntimeError: No edges loaded.

**Comment by JHMeusener** [comment]
no idea, seems to be a different code?
